// Code generated by "stringer -type Phase -trimprefix Phase"; DO NOT EDIT.

package service

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PhaseUnspecified-0]
	_ = x[PhaseWaiting-1]
	_ = x[PhaseInitializing-2]
	_ = x[PhaseRunning-3]
	_ = x[PhaseShuttingDown-4]
	_ = x[PhaseError-5]
	_ = x[PhaseStopped-6]
}

const _Phase_name = "UnspecifiedWaitingInitializingRunningShuttingDownErrorStopped"

var _Phase_index = [...]uint8{0, 11, 18, 30, 37, 49, 54, 61}

func (i Phase) String() string {
	if i < 0 || i >= Phase(len(_Phase_index)-1) {
		return "Phase(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Phase_name[_Phase_index[i]:_Phase_index[i+1]]
}
